import '../common.dart';

final dataTypes = [
  Bout,
  BoutAction,
  BoutConfig,
  BoutResultRule,
  Club,
  AgeCategory,
  CompetitionBout,
  CompetitionLineup,
  CompetitionParticipation,
  CompetitionPerson,
  CompetitionSystemAffiliation,
  CompetitionWeightCategory,
  Membership,
  Organization,
  AthleteBoutState,
  Person,
  Team,
  TeamClubAffiliation,
  Division,
  DivisionWeightClass,
  League,
  LeagueTeamParticipation,
  LeagueWeightClass,
  TeamMatchParticipation,
  TeamLineup,
  TeamMatchBout,
  AbstractUser,
  User,
  SecuredUser,
  WeightClass,
  WrestlingEvent
];
