import 'package:wrestling_scoreboard_common/common.dart';
/// This file is generated, DO NOT CHANGE BY HAND.

/// Topo-Hierarchically ordered data types (most to least dependent on others).
final dataTypes = [
  TeamMatchParticipation,
  TeamMatchBout,
  LeagueWeightClass,
  DivisionWeightClass,
  CompetitionParticipation,
  CompetitionBout,
  CompetitionWeightCategory,
  WeightClass,
  User,
  TeamMatch,
  TeamLineup,
  TeamClubAffiliation,
  LeagueTeamParticipation,
  Team,
  SecuredUser,
  CompetitionLineup,
  BoutAction,
  Bout,
  AthleteBoutState,
  Membership,
  CompetitionPerson,
  Person,
  League,
  Division,
  CompetitionSystemAffiliation,
  Competition,
  Club,
  AgeCategory,
  Organization,
  BoutResultRule,
  BoutConfig
];

String getTableNameFromType(Type t) {
  return switch (t) {
    const (BoutConfig) => BoutConfig.cTableName,
    const (BoutResultRule) => BoutResultRule.cTableName,
    const (Organization) => Organization.cTableName,
    const (AgeCategory) => AgeCategory.cTableName,
    const (Club) => Club.cTableName,
    const (Competition) => Competition.cTableName,
    const (CompetitionSystemAffiliation) => CompetitionSystemAffiliation.cTableName,
    const (Division) => Division.cTableName,
    const (League) => League.cTableName,
    const (Person) => Person.cTableName,
    const (CompetitionPerson) => CompetitionPerson.cTableName,
    const (Membership) => Membership.cTableName,
    const (AthleteBoutState) => AthleteBoutState.cTableName,
    const (Bout) => Bout.cTableName,
    const (BoutAction) => BoutAction.cTableName,
    const (CompetitionLineup) => CompetitionLineup.cTableName,
    const (SecuredUser) => SecuredUser.cTableName,
    const (Team) => Team.cTableName,
    const (LeagueTeamParticipation) => LeagueTeamParticipation.cTableName,
    const (TeamClubAffiliation) => TeamClubAffiliation.cTableName,
    const (TeamLineup) => TeamLineup.cTableName,
    const (TeamMatch) => TeamMatch.cTableName,
    const (User) => User.cTableName,
    const (WeightClass) => WeightClass.cTableName,
    const (CompetitionWeightCategory) => CompetitionWeightCategory.cTableName,
    const (CompetitionBout) => CompetitionBout.cTableName,
    const (CompetitionParticipation) => CompetitionParticipation.cTableName,
    const (DivisionWeightClass) => DivisionWeightClass.cTableName,
    const (LeagueWeightClass) => LeagueWeightClass.cTableName,
    const (TeamMatchBout) => TeamMatchBout.cTableName,
    const (TeamMatchParticipation) => TeamMatchParticipation.cTableName,
    const (BasicAuthService) => BasicAuthService.cTableName, // Only used for type encoding
    _ => throw UnimplementedError('ClassName for "${t.toString()}" not found.'),
  };
}

Type getTypeFromTableName(String tableName) {
  return switch (tableName) {
    BoutConfig.cTableName => BoutConfig,
    BoutResultRule.cTableName => BoutResultRule,
    Organization.cTableName => Organization,
    AgeCategory.cTableName => AgeCategory,
    Club.cTableName => Club,
    Competition.cTableName => Competition,
    CompetitionSystemAffiliation.cTableName => CompetitionSystemAffiliation,
    Division.cTableName => Division,
    League.cTableName => League,
    Person.cTableName => Person,
    CompetitionPerson.cTableName => CompetitionPerson,
    Membership.cTableName => Membership,
    AthleteBoutState.cTableName => AthleteBoutState,
    Bout.cTableName => Bout,
    BoutAction.cTableName => BoutAction,
    CompetitionLineup.cTableName => CompetitionLineup,
    SecuredUser.cTableName => SecuredUser,
    Team.cTableName => Team,
    LeagueTeamParticipation.cTableName => LeagueTeamParticipation,
    TeamClubAffiliation.cTableName => TeamClubAffiliation,
    TeamLineup.cTableName => TeamLineup,
    TeamMatch.cTableName => TeamMatch,
    User.cTableName => User,
    WeightClass.cTableName => WeightClass,
    CompetitionWeightCategory.cTableName => CompetitionWeightCategory,
    CompetitionBout.cTableName => CompetitionBout,
    CompetitionParticipation.cTableName => CompetitionParticipation,
    DivisionWeightClass.cTableName => DivisionWeightClass,
    LeagueWeightClass.cTableName => LeagueWeightClass,
    TeamMatchBout.cTableName => TeamMatchBout,
    TeamMatchParticipation.cTableName => TeamMatchParticipation,
    BasicAuthService.cTableName => BasicAuthService, // Only used for type decoding
    _ => throw UnimplementedError('Type for "${tableName.toString()}" not found.'),
  };
}

Future<int?> handleGenericJson(
  Map<String, dynamic> json, {
  required HandleSingleCallback handleSingle,
  required HandleManyCallback handleMany,
  required HandleSingleRawCallback handleSingleRaw,
  required HandleManyRawCallback handleManyRaw,
}) {
  final type = getTypeFromTableName(json['tableName'] as String);
  return switch (type) {
    const (BoutConfig) => handleJson<BoutConfig>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (BoutResultRule) => handleJson<BoutResultRule>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (Organization) => handleJson<Organization>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (AgeCategory) => handleJson<AgeCategory>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (Club) => handleJson<Club>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (Competition) => handleJson<Competition>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (CompetitionSystemAffiliation) => handleJson<CompetitionSystemAffiliation>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (Division) => handleJson<Division>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (League) => handleJson<League>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (Person) => handleJson<Person>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (CompetitionPerson) => handleJson<CompetitionPerson>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (Membership) => handleJson<Membership>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (AthleteBoutState) => handleJson<AthleteBoutState>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (Bout) => handleJson<Bout>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (BoutAction) => handleJson<BoutAction>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (CompetitionLineup) => handleJson<CompetitionLineup>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (SecuredUser) => handleJson<SecuredUser>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (Team) => handleJson<Team>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (LeagueTeamParticipation) => handleJson<LeagueTeamParticipation>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (TeamClubAffiliation) => handleJson<TeamClubAffiliation>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (TeamLineup) => handleJson<TeamLineup>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (TeamMatch) => handleJson<TeamMatch>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (User) => handleJson<User>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (WeightClass) => handleJson<WeightClass>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (CompetitionWeightCategory) => handleJson<CompetitionWeightCategory>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (CompetitionBout) => handleJson<CompetitionBout>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (CompetitionParticipation) => handleJson<CompetitionParticipation>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (DivisionWeightClass) => handleJson<DivisionWeightClass>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (LeagueWeightClass) => handleJson<LeagueWeightClass>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (TeamMatchBout) => handleJson<TeamMatchBout>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    const (TeamMatchParticipation) => handleJson<TeamMatchParticipation>(json, handleSingle: handleSingle, handleMany: handleMany, handleSingleRaw: handleSingleRaw, handleManyRaw: handleManyRaw),
    _ => throw UnimplementedError('Cannot handle Json for type "${type.toString()}".'),
  };
}
