name: wrestling_scoreboard_generator
description: Generated files from wrestling_scoreboard_common
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  source_gen: ^2.0.0
  build: ^2.4.2
  build_runner: ^2.3.0
  analyzer: ^7.4.4
  glob: ^2.1.3
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
