include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.

linter:
  rules:
    prefer_relative_imports: true
    avoid_print: true


# Needed for freezed package:
analyzer:
  errors:
    invalid_annotation_target: ignore

formatter:
  page_width: 120
