include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.

linter:
  rules:
    - prefer_relative_imports
    - avoid_print
    - prefer_single_quotes
    - prefer_final_locals

# Needed for freezed package:
analyzer:
  errors:
    invalid_annotation_target: ignore

formatter:
  page_width: 120
