targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true

builders:
  genericDataObjectBuilder:
    import: "package:wrestling_scoreboard_generator/builder.dart"
    builder_factories: ["genericDataObjectBuilder"]
    build_extensions: {".dart": ["generic_data_objects.dart"]}
    build_to: source
    required_inputs: [".freezed.dart", ".g.dart"]
    auto_apply: root_package

