name: wrestling_scoreboard_common
description: Collection of common code for wrestling scoreboard client and server.
version: 0.0.1-beta.12
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  country: ^4.1.3
  http: ^1.2.1
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.3.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.16.0
