name: wrestling_scoreboard_common
description: Collection of common code for wrestling scoreboard client and server.
version: 0.1.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1
  freezed_annotation: ^3.0.0
  country: ^5.0.0
  http: ^1.2.1
  collection: ^1.18.0
  logging: ^1.2.0
  crypto: ^3.0.5

dev_dependencies:
  build_runner: ^2.3.0
  freezed: ^3.0.3
  json_serializable: ^6.7.1
  lints: ^5.1.1
  test: ^1.16.0
