name: server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
#   path: ^1.8.
  dotenv: ^3.0.0
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  common:
    path: ../common
  postgres: ^2.4.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
