name: server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#   path: ^1.8.
  dotenv: ^3.0.0
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  common:
    path: ../common

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
