name: server
description: Server for a wrestling scoreboard.
version: 1.0.0
homepage: https://server.wrestling-scoreboard.oberhauser.dev
publish_to: 'none'

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  dotenv: ^4.1.0
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  common:
    path: ../common
  postgres: ^2.4.0
  web_socket_channel: ^2.1.0
  shelf_web_socket: ^1.0.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0
