name: wrestling_scoreboard_macros
description: Macros for wrestling scoreboard.
version: 0.0.1
publish_to: 'none'
repository: https://github.com/Oberhauser-Dev/wrestling_scoreboard/tree/main/wrestling_scoreboard_macros

environment:
  sdk: ^3.4.0

dependencies:
  macros: ^0.1.0-main.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
