name: common
description: Collection of common code for wrestling scoreboard client and server.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.6.1
  lints: ^2.0.1
  test: ^1.16.0
