name: wrestling_scoreboard_client
description: Wrestling software for managing team matches and competitions.

publish_to: 'none'

homepage: 'https://wrestling-scoreboard.oberhauser.dev'
repository: 'https://github.com/Oberhauser-Dev/wrestling_scoreboard/tree/main/wrestling_scoreboard_client'
version: 0.0.1-beta.9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.18.0
  http: ^1.1.0
  dropdown_search: ^5.0.6
  audioplayers: ^6.0.0
  web_socket_channel: ^2.3.0
  go_router: ^13.2.1
  path_provider: ^2.0.8
  shared_preferences: ^2.0.13
  wrestling_scoreboard_common:
    path: ../wrestling_scoreboard_common
  pdf: ^3.10.1
  printing: ^5.11.1  
  url_launcher: ^6.2.2
  package_info_plus: ^6.0.0
  flutter_markdown: ^0.6.18+2
  google_fonts: ^6.1.0
  window_manager: ^0.3.8
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  collection: ^1.18.0
  country: ^4.1.3
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  riverpod_generator: ^3.0.0-dev.11
  build_runner: ^2.4.7

# TODO(gustl22): Remove when published: https://github.com/rrousselGit/riverpod/commit/d7816cfc6748d9df0f0d9e75e75834f1c89714dc
dependency_overrides:
  riverpod:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod
      ref: 28d70d0 # dev
  flutter_riverpod:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/flutter_riverpod
      ref: 28d70d0 # dev
  riverpod_annotation:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod_annotation
      ref: 28d70d0 # dev
  riverpod_generator:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod_generator
      ref: 28d70d0 # dev
  riverpod_analyzer_utils:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod_analyzer_utils
      ref: 28d70d0 # dev

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/icons/
    - CHANGELOG.md

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icons/launcher.png"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
