name: wrestling_scoreboard_client
description: Wrestling software for managing team matches and competitions.

resolution: workspace
publish_to: 'none'

homepage: 'https://wrestling-scoreboard.oberhauser.dev'
repository: 'https://github.com/Oberhauser-Dev/wrestling_scoreboard/tree/main/wrestling_scoreboard_client'
version: 0.3.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.1.0
  dropdown_search: ^6.0.1
  audioplayers: ^6.0.0
  web_socket_channel: ^3.0.1
  go_router: ^16.0.0
  path_provider: ^2.0.8
  shared_preferences: ^2.0.13
  wrestling_scoreboard_common:
    path: ../wrestling_scoreboard_common
  pdf: ^3.11.1
  printing: ^5.14.2
  url_launcher: ^6.2.2
  package_info_plus: ^8.0.1
  flutter_markdown: ^0.7.1
  google_fonts: ^6.1.0
  window_manager: ^0.5.1
  flutter_riverpod: ^3.0.0-dev.16
  riverpod_annotation: ^3.0.0-dev.16
  collection: ^1.18.0
  country: ^6.0.0
  file_selector: ^1.0.3
  csv: ^6.0.0
  web: ^1.0.0
  material_duration_picker: ^0.0.2
  scrollable_positioned_list: ^0.3.8
  pub_semver: ^2.1.4
  linked_scroll_controller: ^0.2.0
  async: ^2.13.0
  logging: ^1.3.0
  path: ^1.9.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0-dev.16
  build_runner: ^2.4.7
  riverpod_lint: ^3.0.0-dev.16
  freezed: ^3.1.0
  json_serializable: ^6.9.5

dependency_overrides:
  # TODO(gustl22): Remove when published: https://github.com/DavBfr/dart_pdf/pull/1736
  pdf:
    git:
      url: https://github.com/Gustl22/dart_pdf.git
      path: pdf
      ref: 313-column-span

flutter:
  generate: true
  uses-material-design: true

  assets:
    - CHANGELOG.md
    - assets/audio/
    - assets/docs/
    - assets/images/icons/
    - assets/fonts/google/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icons/launcher.png"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
