name: wrestling_scoreboard_client
description: Wrestling software for managing team matches and competitions.

resolution: workspace
publish_to: 'none'

homepage: 'https://wrestling-scoreboard.oberhauser.dev'
repository: 'https://github.com/Oberhauser-Dev/wrestling_scoreboard/tree/main/wrestling_scoreboard_client'
version: 0.1.2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.1.0
  dropdown_search: ^6.0.1
  audioplayers: ^6.0.0
  web_socket_channel: ^3.0.1
  go_router: ^14.1.1
  path_provider: ^2.0.8
  shared_preferences: ^2.0.13
  wrestling_scoreboard_common:
    path: ../wrestling_scoreboard_common
  pdf: ^3.11.1
  printing: ^5.14.2
  url_launcher: ^6.2.2
  package_info_plus: ^8.0.1
  flutter_markdown: ^0.7.1
  google_fonts: ^6.1.0
  window_manager: ^0.4.3
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  collection: ^1.18.0
  country: ^5.0.0
  file_selector: ^1.0.3
  csv: ^6.0.0
  web: ^1.0.0
  material_duration_picker: ^0.0.2
  scrollable_positioned_list: ^0.3.8
  pub_semver: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.0-dev.11
  build_runner: ^2.4.7

dependency_overrides:
  # TODO(gustl22): Remove when published: https://github.com/DavBfr/dart_pdf/pull/1736
  pdf:
    git:
      url: https://github.com/Gustl22/dart_pdf.git
      path: pdf
      ref: 313-column-span
  # TODO(gustl22): Remove when published: https://github.com/rrousselGit/riverpod/commit/d7816cfc6748d9df0f0d9e75e75834f1c89714dc
  riverpod:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod
      ref: 1c7a5db # dev
  flutter_riverpod:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/flutter_riverpod
      ref: 1c7a5db # dev
  riverpod_annotation:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod_annotation
      ref: 1c7a5db # dev
  riverpod_generator:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod_generator
      ref: 1c7a5db # dev
  riverpod_analyzer_utils:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod_analyzer_utils
      ref: 1c7a5db # dev

flutter:
  generate: true
  uses-material-design: true

  assets:
    - CHANGELOG.md
    - assets/audio/
    - assets/docs/
    - assets/images/icons/
    - assets/fonts/google/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icons/launcher.png"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
