name: build
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  call-test:
    uses: ./.github/workflows/test.yml
  call-build-client:
    needs:
      - call-test
    uses: ./.github/workflows/build-client.yml
    with:
      upload_pages_artifact: true

  deploy-client:
    needs:
      - call-build-client
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
  deploy-server:
    name: Deploy Server for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
      - uses: bluefireteam/melos-action@v3
      - name: Deploy
        uses: oberhauser-dev/dart-release-action@v0
        with:
          working-directory: wrestling_scoreboard_server
          dry-run: false
          main-path: 'bin/server.dart'
          app-name: 'wrestling_scoreboard_server'
          build-metadata: nightly.${GITHUB_SHA::7}
          tag: ${{ github.ref }}
          token: ${{ github.token }}
          # build-args: |-
          include-paths: |-
            public
            database
            .env.example
            pubspec.yaml
          # Deploy
          deploy-web-host: ${{ secrets.WEB_HOST }}
          deploy-web-path: ${{ secrets.SERVER_DEPLOY_PATH_DEV }}
          deploy-web-ssh-port: ${{ secrets.WEB_SSH_PORT }}
          deploy-web-ssh-user: ${{ secrets.WEB_SSH_USER }}
          deploy-web-ssh-private-key-base64: ${{ secrets.WEB_SSH_PRIVATE_KEY }}
          deploy-pre-run: |
            systemctl --user stop wrestling-scoreboard-server-dev.service
          deploy-post-run: |
            systemctl --user start wrestling-scoreboard-server-dev.service


