name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release-server:
    name: Release Server for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: macos
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.2'
          channel: 'stable'
      - name: Build
        run: ./build.sh -v ${{ github.ref_name }}
        working-directory: wrestling_scoreboard_server
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: ./wrestling_scoreboard_server/build/wrestling-scoreboard-server-${{ github.ref_name }}-${{ matrix.platform }}-x86_64.tar.gz
          asset_name: wrestling-scoreboard-server-${{ github.ref_name }}-${{ matrix.platform }}-x86_64.tar.gz
          tag: ${{ github.ref }}
    
  release-client:
    name: Release Client for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: wrestling_scoreboard_client
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: Android
            release-type: apk
          - os: windows-latest
            platform: Windows
            release-type: windows
          - os: ubuntu-latest
            platform: Linux
            release-type: debian
          - os: ubuntu-latest
            platform: Web
            release-type: web
          - os: macos-latest
            platform: macOS
            release-type: macos
#          - os: macos-latest
#            platform: iOS
#            release-type: ipa
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.2'
          channel: 'stable'
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libunwind-dev
          sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
        if: ${{ matrix.platform == 'Linux' }}
      - name: Build
        uses: oberhauser-dev/flutter-release-action@v0
        with:
          app-name: 'wrestling_scoreboard_client'
          app-version: ${{ github.ref_name }}
          tag: ${{ github.ref }}
          release-type: ${{ matrix.release-type }}
          token: ${{ github.token }}
          build-args: |-
            --dart-define=APP_ENVIRONMENT=production
            --dart-define=API_URL=https://server.wrestling-scoreboard.oberhauser.dev/api
            --dart-define=WEB_SOCKET_URL=wss://server.wrestling-scoreboard.oberhauser.dev/ws
            --dart-define=USE_PATH_URL_STRATEGY=true
          working-directory: wrestling_scoreboard_client

