name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: wrestling_scoreboard_client
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: Android
            release-type: apk
          - os: windows-latest
            platform: Windows
            release-type: windows
          - os: ubuntu-latest
            platform: Linux
            release-type: debian
          - os: ubuntu-latest
            platform: Web
            release-type: web
          - os: macos-latest
            platform: macOS
            release-type: macos
#          - os: macos-latest
#            platform: iOS
#            release-type: ipa
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libunwind-dev
          sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
        if: ${{ matrix.platform == 'Linux' }}
      - name: Build
        uses: oberhauser-dev/flutter-release-action@v0
        with:
          app-name: 'wrestling_scoreboard_client'
          app-version: ${{ github.ref_name }}
          tag: ${{ github.ref }}
          release-type: ${{ matrix.release-type }}
          token: ${{ github.token }}
          build-args: |-
            --dart-define=APP_ENVIRONMENT=development
            --dart-define=API_URL=https://server.wrestling-scoreboard.oberhauser.dev/api
            --dart-define=WEB_SOCKET_URL=wss://server.wrestling-scoreboard.oberhauser.dev/ws
          working-directory: wrestling_scoreboard_client

