name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: android
            build_cmd: apk
            artifact_path: android/app.apk
            asset_name: wrestling-scoreboard-client.apk
            
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
      - name: Get dependencies
        run: flutter pub get
      - name: Start release build
        working-directory: wrestling_scoreboard_client
        run: flutter build ${{ matrix.build_cmd }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ matrix.artifact_path }}
          asset_name: ${{ matrix.asset_name }}-${{github.ref_name}}
          tag: ${{ github.ref }}
